### ISSUE TITLE
only works on square resolutions

### ISSUE THREAD

**Issue by frankyifei** [wildminder/ComfyUI-DyPE#2]
Other resolutions result in distorted photos.

**Comment by alessandroperilli** [comment]
I have the same problem. Here 3 examples when I ask for a 4K (3840x2160) image:

One-word prompt:
![Image](https://github.com/user-attachments/assets/e9685ba6-2ee6-415f-b6ad-746a98742be7)

Long prompt:
![Image](https://github.com/user-attachments/assets/a9a15aa6-4fb8-41c7-8683-7d952bd11c67)

Long prompt + LoRA:
![Image](https://github.com/user-attachments/assets/f1fbbc62-2654-4fc9-8176-a8a130ab2dd4)

I saw the warning about the bug with the node's width and length, so I tried with both explicit size definitions and by just leaving 1024x1024:

<img width="1130" height="1060" alt="Image" src="https://github.com/user-attachments/assets/230fa76e-86fe-4c32-9d1e-6aa3190c348e" />

(BTW, another problem I have is that the node doesn't seem to make any difference if I change the base/max shift, but it's secondary compared to the main issue)

I am using the official BFL FLUX.1 Dev model in BF16 precision.

Finally, my ComfyUI environment is:
<img width="1408" height="668" alt="Image" src="https://github.com/user-attachments/assets/fe8c92e8-f993-4839-bc19-ecc34f4f331a" />

Let me know if I can provide additional info. 

I would love to include this node in the next release of [Open Creative Studio](https://oc.studio), but I need to figure out what's wrong.

**Comment by alessandroperilli** [comment]
Sure:

`Cinematic, Detailed, HD medium shot size photo of Superman, shot on ARRI ALEXA 65`

Can you please try 3840x2160?
3840x1024 really seems a stretch.

Thanks!

**Comment by alessandroperilli** [comment]
I'd say this mostly matches my experience. Of course, we have used different seeds here. 
Unfortunately, at least IMO, the body size is really disproportionate, as if the model is trying to fill a specific % of the image size with the main subject.

I'll other tests with non-human subjects. Thank you.

**Comment by LinuxLurker707** [comment]
Flux-Krea, 3060 12GB, 32GB RAM, Custom LoRA, Sage Node removed, Original image size 27MB, Rendered in 1 hour 54 mins!! Thank you @guyyariv @wildminder !!! Below is a screengrab of the original image as file size is 27MB. 

<img width="937" height="919" alt="Image" src="https://github.com/user-attachments/assets/d6ed4960-a077-4f41-b9b7-fefc49d1c14a" />

**Comment by wildminder** [comment]
@alessandroperilli 
I fixed the stretching issue, but got grainy artifacts.

![Image](https://github.com/user-attachments/assets/fb378a0a-0fc7-4a95-b6df-0c18d08d8c82)

<img alt="Image" src="https://github.com/user-attachments/assets/3bd30bfa-e6f0-4f05-96d9-5a6e44ce54b8" />

<img  alt="Image" src="https://github.com/user-attachments/assets/75655d74-8b72-4717-8805-7221e77afdea" />

**Comment by alessandroperilli** [comment]
I think the image of superman still shows high disproportion, but only on the X axis. The Y axis seems fine now.
The other two images look infinitely more proportioned.

Shame for the artifacts. It looks as if all the noise that was previously used to create the main subject's details is now scattered everywhere, and interpreted as grain/sand/snow/generic artifact. 
But this is very promising now.

**Comment by edonero21-art** [comment]
Hi everyone! I´m having the same issue here, the subject is stretched on both axis whether on horizontal or vertical aspect ratios, I remember that in Forge WebUI there was an option called Kohya HRfix, that addon alone completely corrects the stretching of the images and the subject proportions.

After searching there´s a node called: "PatchModelAddDownscale (Kohya Deep Shrink)", you can connect it, I assume, anywhere after the DyPE node, set both the Blocks and the Downscale factor values between 3, 4 or 5, depending on your desire resolution, and it should correct the stretching issues, at least it did it for me 😃 

For a 2048x3072 res image, Blocks: 5, Downscale: 3, worked just fine. As per my understanding, it downscales the latent image, and divides it in blocks, and that is what helps to correct the stretching of the subject/object. 

Happy diffusion everyone!

**Comment by jewelsonn** [comment]
I think the character stretching you're experiencing with 21:9 aspect ratios in normal FLUX models is completely normal and expected behavior due to Technical limitation of Diffusion Transformers, not a bug. Although when I used Nunchaku flux I had no issues because of how different technique nunchaku handles when using the diffusion transformers. The only issue was duplication instead of streatching in nunchaku SQVD models. 

Below Image is 3840 x 1280, 20 Steps on Euler - Beta with 1 CFG  using _sqvd-fp4_r32-flux.1-krea-dev_ with torch Compile + Sage Attention.

<img width="3840" height="1280" alt="Image" src="https://github.com/user-attachments/assets/ffaa0974-0933-44fd-ab16-894eaa759455" />

**Comment by a3nima** [comment]
@jewelsonn so you generate in a regular resolution without the dype patch and add this (on your screenshot) including dype-patched model for highres fix - upscaling?

**Comment by jewelsonn** [comment]
> [@jewelsonn](https://github.com/jewelsonn) so you generate in a regular resolution without the dype patch and add this (on your screenshot) including dype-patched model for highres fix - upscaling?

I generated all results with DyPE  patched model.
The superman one is Without HiRes Fix. It's 100% DyPE 3840 x 1280 Resolution.
The Workflow Screenshot above is First made in Regular Resolution  of 832 x 1216  (With Dype Patch) immedietely followed by HiRes Fix which uses the model DyPE patched model (View that _hires_ckpt_name_ within the Yellow **_HiRes Fix Script_** Node) to upscale 3x the size. It's mostly doing Image-to-Image when doing a hires fix.

**Comment by a3nima** [comment]
would you mind to post your workflow with the hiresfix script? I've tried to recreate but always get outputs like that:

<img width="1446" height="878" alt="Image" src="https://github.com/user-attachments/assets/d0356495-fca5-4f8b-bc46-a7795f7e27e9" />
